- name: Install required packages
  apt: pkg={{ item }}
  become: yes
  with_items:
  - git
  - build-essential
  - automake
  - libcurl4-openssl-dev
  - libssl-dev
  - libgmp-dev
  - zlib1g-dev

- name: Get cpuminer-opt
  git: repo=https://github.com/JayDDee/cpuminer-opt.git dest=~/cpuminer-opt

- name: Build
  command: ./build.sh chdir=~/cpuminer-opt
